In [3]:
import time
import numpy as np

In [4]:
x = np.random.random(100000000)

In [5]:
start = time.time()
sum(x)/len(x)
print(time.time() - start)

16.990285634994507


In [6]:
start = time.time()
np.mean(x)
print(time.time()-start)

0.11393451690673828


In [7]:
x = np.array([1,2,3,4,5])

In [8]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
x.dtype

dtype('int32')

In [10]:
x.shape

(5,)

In [12]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
Y.shape

(4, 3)

In [14]:
Y.size

12

In [15]:
x = np.array(['Hello', 'World'])
print(x)

['Hello' 'World']


In [16]:
print('shape:',x.shape)
print('type:',type(x))
print('dtype:', x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [17]:
x = np.array(['Hello', 'World', 1, 2])
print(x)
print('shape:',x.shape)
print('type:',type(x))
print('dtype:', x.dtype)

['Hello' 'World' '1' '2']
shape: (4,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [19]:
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x)
print('dtype:', x.dtype)

[1 2 3]
dtype: int64


In [20]:
%whos

Variable   Type       Data/Info
-------------------------------
Y          ndarray    4x3: 12 elems, type `int32`, 48 bytes
np         module     <module 'numpy' from 'F:\<...>ges\\numpy\\__init__.py'>
start      float      1581738530.6171956
time       module     <module 'time' (built-in)>
x          ndarray    3: 3 elems, type `int64`, 24 bytes


In [21]:
np.save('169_Numpy', x)

In [22]:
y = np.load('169_Numpy.npy')
print(y)

[1 2 3]


#### Using Built-in Functions to Create ndarrays

In [24]:
x = np.zeros((3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
X = np.full((3,4),2)
print(X)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [26]:
print(X.dtype)

int32


In [28]:
# Identity Matrix
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
# Diagonal Matrix
X = np.diag([10, 20, 30, 40])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [30]:
X = np.arange(10)
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
X = np.arange(4, 10)
print(X)

[4 5 6 7 8 9]


In [32]:
X = np.arange(1, 14, 3)
print(X)

[ 1  4  7 10 13]


In [33]:
X = np.linspace(0,25,10)
print(X)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [34]:
X = np.linspace(0,25,10 ,endpoint=False)
print(X)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [36]:
x = np.arange(20)
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [37]:
Y = np.arange(20).reshape(10,2)
print(Y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [38]:
X = np.random.normal(0,0.1, size=(1000,1000))
print(X)

[[ 0.04627666 -0.17067779 -0.08451946 ... -0.01745521 -0.00439686
  -0.01863614]
 [-0.02976519  0.21476629 -0.1627341  ... -0.38877277  0.00797668
   0.02061167]
 [ 0.04071223 -0.04470979 -0.08482857 ...  0.01495609 -0.06663241
  -0.05812864]
 ...
 [ 0.03038041  0.02335228 -0.0569069  ... -0.01289359  0.04674844
   0.10407777]
 [ 0.05857717 -0.04611801 -0.00642538 ... -0.01114881  0.01809269
  -0.05612169]
 [-0.11519419  0.16699447  0.00919996 ... -0.12921829  0.00754188
  -0.12301995]]


In [39]:
Y = np.array([1,2,3,4,5])
print(Y)

[1 2 3 4 5]


In [40]:
Y = np.append(Y,6)
print(Y)

[1 2 3 4 5 6]


In [41]:
Y = np.append(Y, [7,8])
print(Y)

[1 2 3 4 5 6 7 8]


In [54]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
W = np.append(Y, [[10,11,12]], axis=0)
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
V = np.append(Y, [[10],[11],[12]], axis=1)
print(V)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [57]:
x = np.array([1,2,5,6,7])
print(x)

[1 2 5 6 7]


In [58]:
x = np.insert(x,2,[3,4])
print(x)

[1 2 3 4 5 6 7]


In [59]:
Y = np.array([[1,2,3],[7,8,9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [61]:
W = np.insert(Y,1,[4,5,6], axis=0)
print(W)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
Y = np.array([1,2])
print(Y)

[1 2]


In [66]:
X = np.array([[3,4],[5,6]])
print(X)

[[3 4]
 [5 6]]


In [67]:
n = np.vstack((X, Y))
print(n)

[[3 4]
 [5 6]
 [1 2]]


In [70]:
w = np.hstack((X, Y.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


### Pandas

In [71]:
import pandas as pd

In [74]:
groceries = pd.Series(data=[30,6,'Yes','No'], index=['eggs','apples','milk','bread'])

In [75]:
groceries

eggs       30
apples      6
milk      Yes
bread      No
dtype: object

In [76]:
groceries.shape

(4,)

In [77]:
groceries.ndim

1

In [78]:
groceries.size

4

In [79]:
groceries.index

Index(['eggs', 'apples', 'milk', 'bread'], dtype='object')

In [80]:
groceries.values

array([30, 6, 'Yes', 'No'], dtype=object)

In [81]:
'banana' in groceries

False

In [82]:
'bread' in groceries

True

### Accessing and Deleting Elements in Pandas Series

In [84]:
groceries['eggs']

30

In [87]:
groceries[['milk','bread']]

milk     Yes
bread     No
dtype: object

In [88]:
groceries[0]

30

In [89]:
groceries[-1]

'No'

In [90]:
groceries[[0,1]]

eggs      30
apples     6
dtype: object

In [91]:
groceries.loc[['eggs','apples']]

eggs      30
apples     6
dtype: object

In [92]:
groceries.iloc[[2,3]]

milk     Yes
bread     No
dtype: object

In [93]:
groceries

eggs       30
apples      6
milk      Yes
bread      No
dtype: object

In [94]:
groceries['eggs'] = 2
groceries

eggs        2
apples      6
milk      Yes
bread      No
dtype: object

In [95]:
groceries.drop('apples')

eggs       2
milk     Yes
bread     No
dtype: object

In [96]:
groceries.drop('apples', inplace=True)

In [97]:
fruits = pd.Series([10,6,3], ['apples','oranges','banana'])
fruits

apples     10
oranges     6
banana      3
dtype: int64

In [98]:
fruits + 2

apples     12
oranges     8
banana      5
dtype: int64

In [99]:
fruits

apples     10
oranges     6
banana      3
dtype: int64

In [100]:
np.sqrt(fruits)

apples     3.162278
oranges    2.449490
banana     1.732051
dtype: float64

In [101]:
np.power(fruits,2)

apples     100
oranges     36
banana       9
dtype: int64

In [102]:
fruits[['apples','oranges']] * 2

apples     20
oranges    12
dtype: int64

In [103]:
# Create a Pandas Series that contains the distance of some planets from the Sun.
# Use the name of the planets as the index to your Pandas Series, and the distance
# from the Sun as your data. The distance from the Sun is in units of 10^6 km

distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6]

planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']

# Create a Pandas Series using the above data, with the name of the planets as
# the index and the distance from the Sun as your data.
dist_planets = pd.Series(data=distance_from_sun, index=planets)

# Calculate the number of minutes it takes sunlight to reach each planet. You can
# do this by dividing the distance from the Sun for each planet by the speed of light.
# Since in the data above the distance from the Sun is in units of 10^6 km, you can
# use a value for the speed of light of c = 18, since light travels 18 x 10^6 km/minute.
time_light = dist_planets / 18

# Use Boolean indexing to select only those planets for which sunlight takes less
# than 40 minutes to reach them.
close_planets = time_light[time_light < 40]

In [104]:
close_planets

Earth     8.311111
Mars     12.661111
Venus     6.011111
dtype: float64

### Creating DataFrames

In [110]:
items = {'Bob':pd.Series([245,25,55], index=['bike','pants','watch']), 'Alice':pd.Series([40,110,500,45], index=['book','glasses','bike','pants'])}

In [107]:
type(items)

dict

In [108]:
shopping_carts = pd.DataFrame(items)
shopping_carts

Bob  Alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     55.0    NaN

In [109]:
items = {'Bob':pd.Series([245,25,55]), 'Alice':pd.Series([40,110,500,45])}
df = pd.DataFrame(items)
df

Bob  Alice
0  245.0     40
1   25.0    110
2   55.0    500
3    NaN     45

In [111]:
sel_shopping_cart = pd.DataFrame(items, index=['pants','book'])
sel_shopping_cart

Bob  Alice
pants  25.0     45
book    NaN     40

In [113]:
sel_shopping_cart = pd.DataFrame(items, index=['glasses','book'], columns=['Alice'])
sel_shopping_cart

Alice
glasses    110
book        40