In [1]:
# Basic Sigmoid

import numpy as np
import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x
    
    Arguments:
    x -- A Scalar
    
    Return:
    s -- sigmoid(x)
    """
    s = 1 / (1 + np.exp(-x))
    return s

In [2]:
basic_sigmoid(3)

0.9525741268224334

In [4]:
x = np.array([1, 2, 3])
basic_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [5]:
def sigmoid_derivative(x):
    s = 1 / (1 + np.exp(-x))
    
    ds = s * (1 - s)
    
    return ds

In [6]:
x = np.array([1,2,3])
print("Sigmoid Derivative(x) = "+ str(sigmoid_derivative(x)))

Sigmoid Derivative(x) = [0.19661193 0.10499359 0.04517666]


In [7]:
def image2vector(image):
    v = image.reshape((image.shape[0], image.shape[1], image.shape[2], 1))
    return v

In [8]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[[[0.67826139]
   [0.29380381]]

  [[0.90714982]
   [0.52835647]]

  [[0.4215251 ]
   [0.45017551]]]


 [[[0.92814219]
   [0.96677647]]

  [[0.85304703]
   [0.52351845]]

  [[0.19981397]
   [0.27417313]]]


 [[[0.60659855]
   [0.00533165]]

  [[0.10820313]
   [0.49978937]]

  [[0.34144279]
   [0.94630077]]]]


In [10]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x, ord = 2, axis=1, keepdims=True)
    x = x / x_norm
    return x

In [11]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [14]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    x = x_exp / x_sum
    return x

In [15]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [16]:
def L1(yhat, y):
    return np.sum(np.abs(yhat-y), axis=0)

In [17]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [28]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.dot(np.abs(yhat-y),np.abs(yhat-y))
    ### END CODE HERE ###
    
    return loss

In [29]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
